# build stage
ARG NODE_VERSION=17.0.1
FROM node:${NODE_VERSION} AS build-stage
#ENV NODE_ENV production

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# RUN npm install
# в зависимости от NODE_ENV будет или не будет ставить dev зависимости
RUN npm ci
# Создана папка /app/build

# Bundle app source
COPY . .


# сбилдит приложение в папку /app/build и захардкодит туда все переменные окружения с префиксом REACT_APP
RUN npm run build


# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/build /usr/share/nginx/html

# подменим env файл чтобы ссылка была на /graphql
RUN rm /usr/share/nginx/html/env.js
COPY ci/env.js /usr/share/nginx/html

# needed this to make React Router work properly
RUN rm /etc/nginx/conf.d/default.conf
COPY ci/nginx.conf /etc/nginx/conf.d

EXPOSE 80

# start the nginx web server
#CMD ["nginx", "-g", "daemon off;"]
